// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using AutoHarvest.Models;
//
//    var fbMarketplaceJson = FbMarketplaceJson.FromJson(jsonString);

namespace AutoHarvest.Models
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class FbMarketplaceJson
    {
        [JsonProperty("__bbox")]
        public Bbox Bbox { get; set; }
    }

    public partial class Bbox
    {
        [JsonProperty("complete")]
        public bool Complete { get; set; }

        [JsonProperty("result")]
        public Result Result { get; set; }

        [JsonProperty("sequence_number")]
        public long SequenceNumber { get; set; }

        [JsonProperty("variables")]
        public Variables Variables { get; set; }

        [JsonProperty("extra_context")]
        public object ExtraContext { get; set; }
    }

    public partial class Result
    {
        [JsonProperty("data")]
        public Data Data { get; set; }

        [JsonProperty("extensions")]
        public Extensions Extensions { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("marketplace_search")]
        public MarketplaceSearch MarketplaceSearch { get; set; }

        [JsonProperty("viewer")]
        public Viewer Viewer { get; set; }

        [JsonProperty("marketplace_seo_page")]
        public object MarketplaceSeoPage { get; set; }

        [JsonProperty("vehicle_model_query")]
        public object VehicleModelQuery { get; set; }

        [JsonProperty("flash_sale_event")]
        public object FlashSaleEvent { get; set; }
    }

    public partial class MarketplaceSearch
    {
        [JsonProperty("feed_units")]
        public FeedUnits FeedUnits { get; set; }
    }

    public partial class FeedUnits
    {
        [JsonProperty("edges")]
        public Edge[] Edges { get; set; }

        [JsonProperty("page_info")]
        public PageInfo PageInfo { get; set; }

        [JsonProperty("session_id")]
        public string SessionId { get; set; }

        [JsonProperty("logging_unit_id")]
        public string LoggingUnitId { get; set; }
    }

    public partial class Edge
    {
        [JsonProperty("node")]
        public Node Node { get; set; }

        [JsonProperty("cursor")]
        public object Cursor { get; set; }

        [JsonProperty("__typename")]
        public string Typename { get; set; }
    }

    public partial class Node
    {
        [JsonProperty("__typename")]
        public string Typename { get; set; }

        [JsonProperty("story_type")]
        public string StoryType { get; set; }

        [JsonProperty("story_key")]
        public string StoryKey { get; set; }

        [JsonProperty("tracking")]
        public string Tracking { get; set; }

        [JsonProperty("listing")]
        public Listing Listing { get; set; }

        [JsonProperty("id")]
        public string Id { get; set; }
    }

    public partial class Listing
    {
        [JsonProperty("__typename")]
        public string Typename { get; set; }

        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("primary_listing_photo")]
        public PrimaryListingPhoto PrimaryListingPhoto { get; set; }

        [JsonProperty("__isMarketplaceListingRenderable")]
        public string IsMarketplaceListingRenderable { get; set; }

        [JsonProperty("listing_price")]
        public ListingPrice ListingPrice { get; set; }

        [JsonProperty("strikethrough_price")]
        public StrikethroughPrice StrikethroughPrice { get; set; }

        [JsonProperty("__isMarketplaceListingWithComparablePrice")]
        public string IsMarketplaceListingWithComparablePrice { get; set; }

        [JsonProperty("comparable_price")]
        public object ComparablePrice { get; set; }

        [JsonProperty("comparable_price_type")]
        public object ComparablePriceType { get; set; }

        [JsonProperty("location")]
        public ListingLocation Location { get; set; }

        [JsonProperty("is_hidden")]
        public bool IsHidden { get; set; }

        [JsonProperty("is_live")]
        public bool IsLive { get; set; }

        [JsonProperty("is_pending")]
        public bool IsPending { get; set; }

        [JsonProperty("is_sold")]
        public bool IsSold { get; set; }

        [JsonProperty("is_viewer_seller")]
        public bool IsViewerSeller { get; set; }

        [JsonProperty("min_listing_price")]
        public object MinListingPrice { get; set; }

        [JsonProperty("max_listing_price")]
        public object MaxListingPrice { get; set; }

        [JsonProperty("marketplace_listing_category_id")]
        public string MarketplaceListingCategoryId { get; set; }

        [JsonProperty("marketplace_listing_title")]
        public string MarketplaceListingTitle { get; set; }

        [JsonProperty("custom_title")]
        public string CustomTitle { get; set; }

        [JsonProperty("custom_sub_titles_with_rendering_flags")]
        public CustomSubTitlesWithRenderingFlag[] CustomSubTitlesWithRenderingFlags { get; set; }

        [JsonProperty("origin_group")]
        public object OriginGroup { get; set; }

        [JsonProperty("pre_recorded_videos")]
        public object[] PreRecordedVideos { get; set; }

        [JsonProperty("__isMarketplaceListingWithChildListings")]
        public string IsMarketplaceListingWithChildListings { get; set; }

        [JsonProperty("parent_listing")]
        public object ParentListing { get; set; }

        [JsonProperty("marketplace_listing_seller")]
        public MarketplaceListingSeller MarketplaceListingSeller { get; set; }

        [JsonProperty("__isMarketplaceListingWithDeliveryOptions")]
        public string IsMarketplaceListingWithDeliveryOptions { get; set; }

        [JsonProperty("delivery_types")]
        public string[] DeliveryTypes { get; set; }
    }

    public partial class CustomSubTitlesWithRenderingFlag
    {
        [JsonProperty("subtitle")]
        public string Subtitle { get; set; }
    }

    public partial class ListingPrice
    {
        [JsonProperty("formatted_amount")]
        public string FormattedAmount { get; set; }

        [JsonProperty("amount_with_offset_in_currency")]
        public string AmountWithOffsetInCurrency { get; set; }

        [JsonProperty("amount")]
        public string Amount { get; set; }
    }

    public partial class ListingLocation
    {
        [JsonProperty("reverse_geocode")]
        public PurpleReverseGeocode ReverseGeocode { get; set; }
    }

    public partial class PurpleReverseGeocode
    {
        [JsonProperty("city")]
        public string City { get; set; }

        [JsonProperty("state")]
        public string State { get; set; }

        [JsonProperty("city_page")]
        public CityPage CityPage { get; set; }
    }

    public partial class CityPage
    {
        [JsonProperty("display_name")]
        public string DisplayName { get; set; }

        [JsonProperty("id")]
        public string Id { get; set; }
    }

    public partial class MarketplaceListingSeller
    {
        [JsonProperty("__typename")]
        public string Typename { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("id")]
        public string Id { get; set; }
    }

    public partial class PrimaryListingPhoto
    {
        [JsonProperty("__typename")]
        public string Typename { get; set; }

        [JsonProperty("image")]
        public Image Image { get; set; }

        [JsonProperty("id")]
        public string Id { get; set; }
    }

    public partial class Image
    {
        [JsonProperty("uri")]
        public Uri Uri { get; set; }
    }

    public partial class StrikethroughPrice
    {
        [JsonProperty("formatted_amount")]
        public string FormattedAmount { get; set; }

        [JsonProperty("amount")]
        public string Amount { get; set; }
    }

    public partial class PageInfo
    {
        [JsonProperty("end_cursor")]
        public string EndCursor { get; set; }

        [JsonProperty("has_next_page")]
        public bool HasNextPage { get; set; }
    }

    public partial class Viewer
    {
        [JsonProperty("marketplace_settings")]
        public MarketplaceSettings MarketplaceSettings { get; set; }

        [JsonProperty("buy_location")]
        public ViewerBuyLocation BuyLocation { get; set; }

        [JsonProperty("marketplace_saved_searches")]
        public MarketplaceSavedSearches MarketplaceSavedSearches { get; set; }
    }

    public partial class ViewerBuyLocation
    {
        [JsonProperty("buy_location")]
        public BuyLocationBuyLocation BuyLocation { get; set; }
    }

    public partial class BuyLocationBuyLocation
    {
        [JsonProperty("location")]
        public BuyLocationLocation Location { get; set; }

        [JsonProperty("id")]
        public string Id { get; set; }
    }

    public partial class BuyLocationLocation
    {
        [JsonProperty("reverse_geocode")]
        public FluffyReverseGeocode ReverseGeocode { get; set; }
    }

    public partial class FluffyReverseGeocode
    {
        [JsonProperty("city")]
        public string City { get; set; }
    }

    public partial class MarketplaceSavedSearches
    {
        [JsonProperty("edges")]
        public object[] Edges { get; set; }
    }

    public partial class MarketplaceSettings
    {
        [JsonProperty("current_marketplace")]
        public CurrentMarketplace CurrentMarketplace { get; set; }
    }

    public partial class CurrentMarketplace
    {
        [JsonProperty("__typename")]
        public string Typename { get; set; }

        [JsonProperty("is_metric_base")]
        public bool IsMetricBase { get; set; }

        [JsonProperty("id")]
        public string Id { get; set; }
    }

    public partial class Extensions
    {
        [JsonProperty("is_final")]
        public bool IsFinal { get; set; }
    }

    public partial class Variables
    {
        [JsonProperty("buyLocation")]
        public BuyLocation BuyLocation { get; set; }

        [JsonProperty("contextual_data")]
        public object ContextualData { get; set; }

        [JsonProperty("count")]
        public long Count { get; set; }

        [JsonProperty("cursor")]
        public object Cursor { get; set; }

        [JsonProperty("flashSaleEventID")]
        public string FlashSaleEventId { get; set; }

        [JsonProperty("hasFlashSaleEventID")]
        public bool HasFlashSaleEventId { get; set; }

        [JsonProperty("marketplaceSearchMetadataCardEnabled")]
        public bool MarketplaceSearchMetadataCardEnabled { get; set; }

        [JsonProperty("params")]
        public Params Params { get; set; }

        [JsonProperty("savedSearchID")]
        public object SavedSearchId { get; set; }

        [JsonProperty("savedSearchQuery")]
        public string SavedSearchQuery { get; set; }

        [JsonProperty("scale")]
        public long Scale { get; set; }

        [JsonProperty("shouldIncludePopularSearches")]
        public bool ShouldIncludePopularSearches { get; set; }

        [JsonProperty("topicPageParams")]
        public TopicPageParams TopicPageParams { get; set; }

        [JsonProperty("vehicleParams")]
        public string VehicleParams { get; set; }
    }

    public partial class BuyLocation
    {
        [JsonProperty("latitude")]
        public double Latitude { get; set; }

        [JsonProperty("longitude")]
        public double Longitude { get; set; }
    }

    public partial class Params
    {
        [JsonProperty("bqf")]
        public Bqf Bqf { get; set; }

        [JsonProperty("browse_request_params")]
        public BrowseRequestParams BrowseRequestParams { get; set; }

        [JsonProperty("custom_request_params")]
        public CustomRequestParams CustomRequestParams { get; set; }
    }

    public partial class Bqf
    {
        [JsonProperty("callsite")]
        public string Callsite { get; set; }

        [JsonProperty("query")]
        public string Query { get; set; }
    }

    public partial class BrowseRequestParams
    {
        [JsonProperty("commerce_enable_local_pickup")]
        public bool CommerceEnableLocalPickup { get; set; }

        [JsonProperty("commerce_enable_shipping")]
        public bool CommerceEnableShipping { get; set; }

        [JsonProperty("commerce_search_and_rp_available")]
        public bool CommerceSearchAndRpAvailable { get; set; }

        [JsonProperty("commerce_search_and_rp_category_id")]
        public object[] CommerceSearchAndRpCategoryId { get; set; }

        [JsonProperty("commerce_search_and_rp_condition")]
        public object CommerceSearchAndRpCondition { get; set; }

        [JsonProperty("commerce_search_and_rp_ctime_days")]
        public object CommerceSearchAndRpCtimeDays { get; set; }

        [JsonProperty("filter_location_latitude")]
        public double FilterLocationLatitude { get; set; }

        [JsonProperty("filter_location_longitude")]
        public double FilterLocationLongitude { get; set; }

        [JsonProperty("filter_price_lower_bound")]
        public long FilterPriceLowerBound { get; set; }

        [JsonProperty("filter_price_upper_bound")]
        public long FilterPriceUpperBound { get; set; }

        [JsonProperty("filter_radius_km")]
        public long FilterRadiusKm { get; set; }
    }

    public partial class CustomRequestParams
    {
        [JsonProperty("browse_context")]
        public object BrowseContext { get; set; }

        [JsonProperty("contextual_filters")]
        public object[] ContextualFilters { get; set; }

        [JsonProperty("referral_code")]
        public object ReferralCode { get; set; }

        [JsonProperty("saved_search_strid")]
        public object SavedSearchStrid { get; set; }

        [JsonProperty("search_vertical")]
        public string SearchVertical { get; set; }

        [JsonProperty("seo_url")]
        public object SeoUrl { get; set; }

        [JsonProperty("surface")]
        public string Surface { get; set; }

        [JsonProperty("virtual_contextual_filters")]
        public object[] VirtualContextualFilters { get; set; }
    }

    public partial class TopicPageParams
    {
        [JsonProperty("location_id")]
        public string LocationId { get; set; }

        [JsonProperty("url")]
        public object Url { get; set; }
    }

    public partial class FbMarketplaceJson
    {
        public static FbMarketplaceJson FromJson(string json)
        {
            return JsonConvert.DeserializeObject<FbMarketplaceJson>(json, AutoHarvest.Models.Converter.Settings);
        }
    }

    public static class Serialize
    {
        public static string ToJson(this FbMarketplaceJson self)
        {
            return JsonConvert.SerializeObject(self, AutoHarvest.Models.Converter.Settings);
        }
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
